<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXfavrxp\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXfavrxp/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXfavrxp.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXfavrxp\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXfavrxp\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Xfavrxp',
    'container.build_id' => 'a50c0896',
    'container.build_time' => 1526977624,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXfavrxp');
